[31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
  execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
  au_interfaces --arguments-file
  /home/zhaocake/Documents/single_program/rm_hotpot_exam/Folder_2_Ros/Au_miner/build/au_interfaces/rosidl_adapter__arguments__au_interfaces.json
  --output-dir
  /home/zhaocake/Documents/single_program/rm_hotpot_exam/Folder_2_Ros/Au_miner/build/au_interfaces/rosidl_adapter/au_interfaces
  --output-file
  /home/zhaocake/Documents/single_program/rm_hotpot_exam/Folder_2_Ros/Au_miner/build/au_interfaces/rosidl_adapter/au_interfaces.idls)
  returned error code 1:

  Error processing ' int32 index' of 'au_interfaces/Mineral_Feedback':
  'string index out of range'

  Traceback (most recent call last):

    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 29, in convert_to_idl
      return convert_action_to_idl(
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/action/__init__.py", line 28, in convert_action_to_idl
      action = parse_action_string(package_name, input_file.stem, content)
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 906, in parse_action_string
      feedback_message = parse_message_string(
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 520, in parse_message_string
      Type(type_string, context_package_name=pkg_name),
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 241, in __init__
      self.is_array = type_string[-1] == ']'

  IndexError: string index out of range

Call Stack (most recent call first):
  /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:15 (rosidl_generate_interfaces)

[0m
